- flask-dashboard/dashboard/database/__init__.py
- flask-dashboard/dashboard/database/tests.py
- flask-dashboard/dashboard/routings/setup.py
- flask-dashboard/templates/default.html
- flask-dashboard/templates/how-to-install.html
- flask-dashboard/templates/how-to-use.html
- flask-dashboard/templates/index.html
- flask-dashboard/templates/login.html
- flask-dashboard/templates/measurements.html
- flask-dashboard/templates/rules.html
- flask-dashboard/templates/settings.html
- flask-dashboard/templates/show-graph.html
- flask-dashboard/templates/testmonitor.html
Search for unit tests within your project, save them, show them, execute them and time them.
Save execution results, create visualization (execution time per version) for the results.
> Unit test monitoring

- flask_monitoringdashboard/measurement.py
- flask_monitoringdashboard/outlier.py
Avoiding the stack snapshotting computation in case we don't have an outlier. 
I wonder if this will be visible in the performance.
> Making sure to stop outlier thread

- flask_monitoringdashboard/database/function_calls.py
- flask_monitoringdashboard/test/db/test_function_calls.py
to be an open range, where the lower bound is exclusive and the upper
bound is inclusive.
> alters the range returned by get_data_between

- flask_monitoringdashboard/database/function_calls.py
- flask_monitoringdashboard/database/versions.py
- flask_monitoringdashboard/test/constants.py
sorry, i raise a wrong pull request to master branch last time...
replace func.strftime with func.date
solve distinct query problem with MySQL
> issue #116

- flask_monitoringdashboard/database/endpoint.py
- flask_monitoringdashboard/templates/fmd_config.html
- flask_monitoringdashboard/views/dashboard/heatmap.py
- requirements.txt
Hi Patrick,
I complete your solution, please have a look~
Harold
> add timezone attr to config file and adjust time series data with corresponding timezone info

- flask_monitoringdashboard/templates/fmd_dashboard/overview.html
Fixes #137
API reference: https://datatables.net/reference/api/order()
> added ordering for datatable

- flask_monitoringdashboard/core/forms/__init__.py
- flask_monitoringdashboard/core/forms/double_slider.py
- flask_monitoringdashboard/core/forms/slider.py
- flask_monitoringdashboard/database/count.py
- flask_monitoringdashboard/database/versions.py
- flask_monitoringdashboard/static/css/custom.css
- flask_monitoringdashboard/templates/fmd_dashboard/overview.html
- flask_monitoringdashboard/test/db/test_count.py
- flask_monitoringdashboard/views/dashboard/heatmap.py
- flask_monitoringdashboard/views/dashboard/requests.py
- flask_monitoringdashboard/views/dashboard/version_usage.py
- flask_monitoringdashboard/views/details/time_version.py
- flask_monitoringdashboard/views/details/version_ip.py
- flask_monitoringdashboard/views/details/version_user.py
Added sliders for selecting a subset of data to show in graphs.
Default slider value set to 10 (versions/users) instead of half of the available data.
Adapted graphs to show most recent data either at the top or at the right of the screen.
Made color of table rows change when hovering.
> Add version sliders

- flask_monitoringdashboard/database/__init__.py
- flask_monitoringdashboard/migrate.py
Update the FunctionCalls schema
> Schema update

- docs/configuration.rst
- flask_monitoringdashboard/__init__.py
- flask_monitoringdashboard/core/config/__init__.py
- flask_monitoringdashboard/core/config/parser.py
- flask_monitoringdashboard/core/group_by.py
- flask_monitoringdashboard/core/logger.py
- flask_monitoringdashboard/core/profiler/outlierProfiler.py
- flask_monitoringdashboard/core/profiler/stacktraceProfiler.py
Implemented logging functionality
> implemented logger

- flask_monitoringdashboard/core/profiler/stacktraceProfiler.py
Fixes: #194 
**Proposed Changes**:
- Added if `_total != 0` check, duration is 0 otherwise
- Also added an extra line above `class StacktraceProfiler` for PEP8 compliance.
> Prevent ZeroDivisionErrors from occurring

- flask_monitoringdashboard/static/elements/monitorLevel.html
- flask_monitoringdashboard/static/js/controllers/monitorLevel.js
- flask_monitoringdashboard/static/js/controllers/overview.js
- flask_monitoringdashboard/static/js/directives.js
- flask_monitoringdashboard/static/pages/overview.html
- flask_monitoringdashboard/static/pages/plotly_graph.html
- flask_monitoringdashboard/templates/fmd_base.html
Changed monitor-level buttons into a directive. This directive takes two argument: <monitorlevel name=[endpoint_name], value=[monitor-level] />.
Logic from this directive is implemented in a controller (MonitorLevelController).
> fixed monitor button

- flask_monitoringdashboard/static/js/filters.js
- flask_monitoringdashboard/static/pages/overview.html
If the filter returns a string, is sorted as a a string, then 2000 < 900
Create a new filter duration_ms for the table and show the unit (ms) in the table header
> Overview: display times in as numbers to make them sortable

- flask_monitoringdashboard/views/deployment.py
- flask_monitoringdashboard/views/endpoint.py
- flask_monitoringdashboard/views/outlier.py
- flask_monitoringdashboard/views/profiler.py
- flask_monitoringdashboard/views/request.py
- flask_monitoringdashboard/views/version.py
The wrong rule paths are as follows:
> Added leading slash to blueprint paths.

- migration/migrate_v2_to_v3.py
Johan's migration script. For some reason, Github didn't recognize the file in a normal PR.
> Add migration script from v2 to v3

- MANIFEST.in
- flask_monitoringdashboard/constants.json
added missing file in Manifest
> Fixing description for pypi

- docs/migration.rst
> updated links to migration scripts

- docs/contact.rst
- flask_monitoringdashboard/core/profiler/stacktraceProfiler.py
- flask_monitoringdashboard/core/reporting/questions/status_code_distribution.py
- flask_monitoringdashboard/database/request.py
- flask_monitoringdashboard/static/elements/endpointDetails.html
- flask_monitoringdashboard/static/pages/grouped_profiler.html
- flask_monitoringdashboard/static/pages/outliers.html
- flask_monitoringdashboard/static/pages/overview.html
- flask_monitoringdashboard/static/pages/plotly_graph.html
- flask_monitoringdashboard/static/pages/profiler.html
- flask_monitoringdashboard/test/views/test_status_code_tracking.py
- flask_monitoringdashboard/views/reporting.py
- migration/migrate_v2_to_v3.py
- Remove unused import
- Initialize `status_code` in `init` method instead of `stop` method
- Clean HTML
> Static check

- flask_monitoringdashboard/static/css/custom.css
- flask_monitoringdashboard/static/pages/overview.html
> fixed the sorting of the columns containing error counts

- flask_monitoringdashboard/test/db/test_endpoint.py
There is a small typo in flask_monitoringdashboard/test/db/test_endpoint.py.
Closes #312
> docs: Fix simple typo, wheter -> whether

- flask_monitoringdashboard/database/custom_graph.py
> Include the selected date into the custom graph end date

- flask_monitoringdashboard/core/config/parser.py
My old pull request (#282) continue to have the bug, now is fixed
> Use a dummy version if no git folder is found

- flask_monitoringdashboard/frontend/package-lock.json
- flask_monitoringdashboard/frontend/package.json
Forgot to add this to PR #322 
@bogdanp05 mentioned that he ran into an error about a missing dependency `webpack`. I didn't run into this problem myself because I have `webpack` globally installed.
This PR will solve this.
Regards,
Johan
> Added webpack to dev dependencies

- flask_monitoringdashboard/database/versions.py
> fixed #336

- flask_monitoringdashboard/controllers/endpoints.py
- flask_monitoringdashboard/core/blueprints.py
- flask_monitoringdashboard/frontend/js/controllers/OverviewController.js
- flask_monitoringdashboard/static/pages/overview.html
- tests/api/test_endpoint.py
- tests/unit/core/test_blueprints.py
Hi - 
I wanted a way to be able to filter by blueprints.
Basically a shortcut to supporting multiple apps with one dashboard without having to make any database changes.
> Adding the ability to filter by 'blueprint' first word before .

- flask_monitoringdashboard/core/measurement.py
> Correctly log werkzeug.exceptions.HTTPExceptions

- docs/contact.rst
- flask_monitoringdashboard/database/data_base_queries/mongo_db_objects.py
@FlyingBird95 picture added! Thank you for your trust!
> Adding contributor picture + Adding more db indexes for mongodb implementation

- flask_monitoringdashboard/static/css/main.css
- flask_monitoringdashboard/static/pages/configuration.html
- flask_monitoringdashboard/templates/fmd_base.html
1. the **dashboard link** on the configuration file was broken so I fixed this
2. I made some changes for better design in devices with small widths for example the nav bar didn't show on mobile phones so I tried to fix this.
> debug and better design for mobile phones

- flask_monitoringdashboard/static/pages/configuration.html
Create user, delete user and edit user modals were broken, so I fixed them.
Additionally the checkboxes were showing up as field inputs, so I removed class formcontrol.
> Fixed create edit delete and checkboxes

- flask_monitoringdashboard/controllers/exceptions.py
- flask_monitoringdashboard/database/exception_info.py
- flask_monitoringdashboard/frontend/js/app.js
- flask_monitoringdashboard/frontend/js/controllers/exceptionInfo.js
- flask_monitoringdashboard/frontend/js/services/menu.js
- flask_monitoringdashboard/static/elements/menu.html
- flask_monitoringdashboard/static/pages/new_dashboard.html
- flask_monitoringdashboard/views/endpoint.py
Create new dashboard displaying exceptions as json.
> Dashboard with Exceptions as json

- flask_monitoringdashboard/controllers/exceptions.py
- flask_monitoringdashboard/database/count.py
- flask_monitoringdashboard/database/exception_info.py
- flask_monitoringdashboard/static/pages/new_dashboard.html
- flask_monitoringdashboard/views/exception.py
Merge new grouped_by changes into our working branch
> ExceptionInfo's grouped by Endpoint.name and full_stack_trace_id

- flask_monitoringdashboard/controllers/exceptions.py
- flask_monitoringdashboard/core/database_pruning.py
- flask_monitoringdashboard/database/exception_info.py
- flask_monitoringdashboard/frontend/js/controllers/endpointException.js
- flask_monitoringdashboard/static/pages/exception_stack_trace.html
- flask_monitoringdashboard/views/exception.py
> You can now delete stack traces

- flask_monitoringdashboard/frontend/js/controllers/endpointException.js
- flask_monitoringdashboard/static/pages/exception_stack_trace.html
fix so that id in frontend is unique at ExceptionStackLines in recursive functions
> unique id in frontend at stack lines in recursive functions

- flask_monitoringdashboard/controllers/exceptions.py
- flask_monitoringdashboard/core/exceptions/stack_frame_parsing.py
- flask_monitoringdashboard/database/exception_frame.py
- flask_monitoringdashboard/database/stack_trace_snapshot.py
- flask_monitoringdashboard/frontend/js/controllers/endpointException.js
- flask_monitoringdashboard/static/pages/exceptions.html
- flask_monitoringdashboard/views/exception.py
function code is the only thing that is fetched separately when unfolding details about lines in the stack trace
removed a lot of divs from frontend but it still looks exactly the same
> function code is the only thing that is fetched separately

- flask_monitoringdashboard/controllers/exceptions.py
- flask_monitoringdashboard/views/exception.py
do you maybe want us to rename the delete_exception_group function Mircea?
> deleted intermediate delete_exceptions_by_stack_trace_id

- docs/changelog.rst
- flask_monitoringdashboard/constants.json
- flask_monitoringdashboard/frontend/sass/custom.css
- flask_monitoringdashboard/static/pages/overview.html
- also made the sorting arrows stand out a bit better.
> Added note about monitoring levels and exceptions at the bottom of the overview page.
